### ISSUE TITLE
storybooks makes outbound request to https://registry.npmjs.org/storybook-addon-react-router-v6/latest

### ISSUE THREAD

**Issue by ferdicus** [JesusTheHun/storybook-addon-remix-react-router#59]
hi there, 
first of all, sorry if there is a related ticket to this, i unfortunately wasn't able to find one :( 

the question at hand would be:
i'm using `storybook-addon-react-router-v6` within my storybook setup. 
on start-up i see, that it's making outbound requests to `https://registry.npmjs.org/storybook-addon-react-router-v6/latest` 
(which i assume are to verify, that it's the latest version?)

i'd like to run my stories in a contained, non connected manner
i've set up MSW to intercept all of my outbound requests (unsuccessfully tried with the mentioned request as well)

can you let me know/ maybe point me towards an answer how to configure/ disable this behavior?

thanks in advance

DEP DETAILS:
    "@storybook/addon-a11y": "^7.6.3",
    "@storybook/addon-essentials": "^7.6.3",
    "@storybook/blocks": "^7.6.3",
    "@storybook/react": "^7.6.3",
    "@storybook/react-vite": "^7.6.3",
    "msw-storybook-addon": "^1.10.0",
    "storybook": "^7.6.3",
    "storybook-addon-react-router-v6": "^2.0.10",

**Comment by JesusTheHun** [comment]
I guess we could have a flag in the globalTypes. Would you mind making a PR for this please ?

**Comment by ferdicus** [comment]
> I guess we could have a flag in the globalTypes. Would you mind making a PR for this please ?

hi there, would gladly open a PR for this, just need a few pointers:

`globalTypes` refers to [this](https://storybook.js.org/docs/essentials/toolbars-and-globals#global-types-and-the-toolbar-annotation)?

would i then add an additional config param like:
```js
  globalTypes: {
    storybookAddonReactRouterV6: {
      addonVersionsFetch: false
    }
  },
```
to it

which is then used in https://github.com/JesusTheHun/storybook-addon-react-router-v6/blob/main/src/features/panel/hooks/useAddonVersions.ts

to conditionally fetch or not? 


thanks in advance 🙇🏿

**Comment by JesusTheHun** [comment]
@ferdicus I'm not sure that's the right option, can I leave you the research ?

**Comment by ferdicus** [comment]
@JesusTheHun , hope you made it safely and relaxed into 2024

Did you find the time to consider my last comment? 


thanks in advance 🙇🏿

**Comment by ferdicus** [comment]
hi there, thanks, all good here :) 

This is a feature that is specifically introduced in this addon via file `src/features/panel/hooks/useAddonVersions.ts` added with this [change](https://github.com/JesusTheHun/storybook-addon-react-router-v6/commit/5e452e99ed8931f9f3bccf26e497fb22ec857f9f)

there is no such thing in this addon we're also using for example: https://github.com/mswjs/msw-storybook-addon

i'm sure the intention is good - but an option to disable this would be great


there is this flag when running storybook: [`--no-version-updates`](https://github.com/storybookjs/storybook/pull/8488)

would be wonderful if this addon could consider that flag within `useAddonVersions`

not sure, how one could access this option within

**Comment by JesusTheHun** [comment]
That would be a good solution indeed. Can you se me if you have access to that information from the storybook hooks ? Or as a fallback, if it's available in the environment ? Either node or browser.

**Comment by JesusTheHun** [comment]
I'm closing this issue as no progress has been done on either side and I don't plan to add it myself. Ping me if you make any progress that you would like to share.

**Comment by andykenward** [comment]
I've used [patch-package](https://www.npmjs.com/package/patch-package) to remove this functionality.
