### ISSUE TITLE
Incompatible with Storybook 8.0.0

### ISSUE THREAD

**Issue by maximsht** [JesusTheHun/storybook-addon-remix-react-router#64]
After updating Storybook to 8.0.0 Storybook Runner shows me an error:

The following packages are incompatible with Storybook 8.0.0 as they depend on different major versions of Storybook packages:
-  storybook-addon-remix-react-router@3.0.0-rc.1
   Repo: https://github.com/JesusTheHun/storybook-addon-remix-react-router#readme

**Comment by JesusTheHun** [comment]
👋 @maximsht thank you for opening an issue !

What is the exact version of Storybook you are using ? I think I wrongfully pinned the version of Storybook to `8.0.0-rc.1`

**Comment by maximsht** [comment]
exact "storybook": "8.0.0",

**Comment by JesusTheHun** [comment]
@maximsht I've published version `v3.0.0`. Can you check with this one ?

**Comment by maximsht** [comment]
I never said it didn't work :-) I said that Storybook notified me, that the plugin is incompatible. It worked well. Now even the notification disappeared. Thanks!
