### ISSUE TITLE
Version 2.0.12 fails on Windows due to `postinstall` using bash syntax

### ISSUE THREAD

**Issue by ldufresnegs** [JesusTheHun/storybook-addon-remix-react-router#65]
**Describe the bug**
Bug was introduced in 6d946e1594d094dbdf6cfec331b6301e352da440, namely the line:
```
    "postinstall": "[ \"$npm_package_name\" = \"storybook-addon-react-router-v6\" ] && sh scripts/announcement.sh || :"
```

**Environment**
Share the output of the following command :
```
  System:
    OS: Windows 11 10.0.22631
```

**Comment by JesusTheHun** [comment]
Hi @ldufresnegs , thanks for reporting this.

It is now fixed, can you try `v2.0.14` and tell me if it ok for you ?

**Comment by ldufresnegs** [comment]
Hi thanks a lot for looking into this.

I've tried again, and this time it complains for an other reason. Looking a bit more into it, it seems that the `announcement.js` file is missing.

Presumably the issue is here: https://github.com/JesusTheHun/storybook-addon-remix-react-router/blob/2fefd707269014366a535cab214325eecff433eb/package.json#L38-L43

**Comment by JesusTheHun** [comment]
@ldufresnegs thanks again for checking. `2.0.15` is out, with the said script ;)

**Comment by ldufresnegs** [comment]
It works, thanks a lot :)
