### ISSUE TITLE
x is not a constructor

### ISSUE THREAD

**Issue by vldslv-a** [JesusTheHun/storybook-addon-remix-react-router#73]
**Describe the bug**
What is supposed to happen ? What is happening instead ?

When I add a plugin to my project and publish it to chromatic, I get an error on "Verifying your Storybook" step:
<img width="786" alt="image" src="https://github.com/user-attachments/assets/e6f24ecb-b3fc-48e8-b889-17451eb80b53">

It works good in development mode. The error starts to occur when using the provider's withRouter.

**Environment**
Share the output of the following command :

```bash
  System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 10.8.3 - ~/Desktop/shop-web/node_modules/.bin/npm <----- active
  Browsers:
    Chrome: 129.0.6668.91
    Safari: 17.5
  npmPackages:
    @storybook/addon-designs: ^8.0.3 => 8.0.3 
    @storybook/addon-essentials: ^8.3.1 => 8.3.1 
    @storybook/addon-interactions: ^8.3.1 => 8.3.1 
    @storybook/addon-links: ^8.3.1 => 8.3.1 
    @storybook/addon-themes: ^8.3.1 => 8.3.1 
    @storybook/blocks: ^8.3.1 => 8.3.1 
    @storybook/react: ^8.3.1 => 8.3.1 
    @storybook/react-vite: ^8.3.1 => 8.3.1 
    @storybook/test: ^8.3.1 => 8.3.1 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.3.1 => 8.3.5 
    storybook-addon-remix-react-router: ^3.0.1 => 3.0.1 
```

```
// preview.ts
export const decorators = [
  withRouter,
  (Story: ComponentType) => (
    <Provider store={store}>
      <Story />
    </Provider>
  ),
];
```

**Comment by JesusTheHun** [comment]
Hi @vldslv-a,

Can you tell if it happens when SB is built and run locally ? Or is it only on chromatic ?

**Comment by vldslv-a** [comment]
When I run it locally, everything works.
When I publish it to chromatic, I get this error.

**Comment by JesusTheHun** [comment]
> When I run it locally, everything works.
So this is a Chromatic issue, not an addon issue.
I suggest you open an issue there.
