### ISSUE TITLE
Allow to set router's futures

### ISSUE THREAD

**Issue by artaommahe** [JesusTheHun/storybook-addon-remix-react-router#76]
**Is your feature request related to a problem? Please describe.**
Since version 6.28.0 react-router-dom spams a lot of warnings about enabling v7 futures in console. storybook-addon-remix-react-router provides no way so set them

**Describe the solution you'd like**
Add `futures` object to `reactRouter` storybook options and pass it to the react-router-dom.

**Describe alternatives you've considered**

\-

**Additional context**
https://reactrouter.com/en/6.27.0/upgrading/future#update-to-latest-v6x
https://github.com/remix-run/react-router/issues/12245

**Comment by JesusTheHun** [comment]
@artaommahe Can you try the canary version ?

`npm i storybook-addon-remix-react-router@3.0.2--canary.8bc91e6.0`

**Comment by artaommahe** [comment]
@JesusTheHun now it works properly for futures passed to the `createBrowserRouter`, but doesn't support futures passed to the `RouterProvider.future` 😅 , like v7_startTransition. So most warnings are finally gone, except one related to v7_startTransition

**Comment by JesusTheHun** [comment]
@artaommahe Oh ok. They gave the same name to two different interfaces.
I've tried locally and it works just fine now :)

```bash
npm i storybook-addon-remix-react-router@3.0.3--canary.73a4e68.0
```

**Comment by artaommahe** [comment]
@JesusTheHun we've already updated to v7 😅
