### ISSUE TITLE
Support for react-router v7

### ISSUE THREAD

**Issue by MartinWeb** [JesusTheHun/storybook-addon-remix-react-router#81]
React-router v7 has been released so if we want to upgrade some components library that use react-router and storybook we would need a new version of storybook-addon-remix-react-router to integrate react-router v7.
Is it something that is planned ? 

The error that we are getting by using the Link component for example : 
![image](https://github.com/user-attachments/assets/98de3233-8462-46a6-ba25-8feb6acb7efa)

**Comment by JesusTheHun** [comment]
Can you provide a stackblitz ?

Version ˋ3.0.2ˋ allows react router v7. It's supposed to be a non-breaking major so I'm surprised you have any issue.

**Comment by MartinWeb** [comment]
Here's what id did to migrate to `react-router` v7 :
I have uninstalled `react-router-dom` and install `react-router` v7 and changed imports to Link from `react-router-dom` to `react-router`.
But in `storybook-addon-remix-react-router` the package used is `react-router-dom`.

Could the root cause be that i have a v7 `react-router` and a v6 `react-router-dom` in my node_modules ?

**Comment by JesusTheHun** [comment]
@MartinWeb it's definitely that. I'll need to update the addon to support either one as a peer dependency

**Comment by MartinWeb** [comment]
Great. Don't hesitate to tell me when you have an RC that i can try before the actual release and i'll give you feedback on it.

**Comment by MartinWeb** [comment]
@JesusTheHun would you like me to try a pull request for that and to add React 19 as peer dependency as well ?

**Comment by JesusTheHun** [comment]
@MartinWeb it's not as simple as shoving a new version number in the package.json

Can you try `npm i storybook-addon-remix-react-router@3.0.3--canary.85.7d8672d.0` ?
It will be a new major version upon release

**Comment by MartinWeb** [comment]
@JesusTheHun the new canary version fixed the problem on my project.
Thanks a lot 👍 
If it's ok for you, you can make a new release.

**Comment by MartinWeb** [comment]
@JesusTheHun any news on a new release to have this correction ? 
Thanks in advance for your reply, and your work on this :)

**Comment by JesusTheHun** [comment]
@MartinWeb this will likely get out Tuesday

**Comment by MartinWeb** [comment]
@JesusTheHun amazing, thanks for the news.
A nice release on new year's eve 👍

**Comment by JesusTheHun** [comment]
@MartinWeb v4.0.0 is out

**Comment by MartinWeb** [comment]
Thanks @JesusTheHun, i will try that next monday :)
