### ISSUE TITLE
Support React 19

### ISSUE THREAD

**Issue by ChristianMurphy** [JesusTheHun/storybook-addon-remix-react-router#83]
**Is your feature request related to a problem? Please describe.**

I'd like to upgrade my project to use React 19, now a stable release: https://react.dev/blog/2024/12/05/react-19

This is currently blocked by a peer dependency allowing up-to, but not past React 18
https://github.com/JesusTheHun/storybook-addon-remix-react-router/blob/334353000e35f289b192f83d663b8c30e0301a07/package.json#L75-L76

**Describe the solution you'd like**
Project to be tested with React 19, and add React 19 to the version range.

**Describe alternatives you've considered**
Wait to upgrade, or don't support React 19.

**Additional context**

**Comment by JesusTheHun** [comment]
Storybook does not support React 19 yet.

See https://github.com/storybookjs/storybook/issues/29805

**Comment by ChristianMurphy** [comment]
It does though.
In the top of the issue

> You should be able to use Storybook with React 19, but if you found any inconsistency or unsupported feature, please let us know in this issue.

It is a call for feedback, not a statement of non-support.

**Comment by Cifixie** [comment]
What's the latest status on this?

**Comment by JesusTheHun** [comment]
@ChristianMurphy @Cifixie v3.1.0 has been released. It includes support for React 19
